### ISSUE TITLE
unify usage of "."s in continuations

### ISSUE THREAD

**Issue by mhtess** [mhtess/elephants#1]
`js/elephants-n.js` use variable sentence continuations. Some of these have the end of the sentence (denoted by a ".") hard-coded into the stimulus file; others dynamically add the "." in the `elephants-n.js` file. This should be unified. Ideally, it should all be handled in the elephants-n.js file.

**Comment by karengu** [comment]
Resolved in 7cd11d458a987bc6483c008e34e1c099df5635ef.
Removed all periods from continuations in `js/stims-n.js` and moved period handling to `js/elephants-n.js`. (Periods in main text remain.) Also removed certain conditions from `present_page` handler `js/elephants-n.js` because they were no longer being used.
